#!/bin/bash
datestamp=$(date +%m-%d-%Y)
#NAS down. Temporarily store locally
#backup_dir="/mnt/nfs-service-backup"
backup_dir="/opt"

docker compose down
tar -cf - \
        -C /opt/ottobot . | gzip -9 > "${backup_dir}/ottobot.tar.gz"
docker compose up -d